### ISSUE TITLE
urllib3 (1.26.2) or chardet (3.0.4) doesn't match a supported version

### ISSUE THREAD

**Issue by RandomVersion** [NotReeceHarris/EconomyDiscord-Bot#1]
Hello.
When i run the bot i get this message

> C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests-2.24.0-py3.7.egg\requests\__init__.py:91:` RequestsDependencyWarning: urllib3 (1.26.2) or chardet (3.0.4) doesn't match a supported version!
>   RequestsDependencyWarning)

(also the bot is cool)

**Comment by NotReeceHarris** [comment]
Hi have you tried updating your pip packages
`$ pip install urllib3`
`$ pip install chardet`
`$ pip install requests`
If this doesn't work message me on discord `ZenoEchozZ#2296`
also this bot is still in development so bugs are common, sorry!

**Comment by RandomVersion** [comment]
The message now dont show but running a command gives this error:

> Ignoring exception in on_message
> Traceback (most recent call last):
>   File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\discord\client.py", line 343, in _run_event
>     await coro(*args, **kwargs)
>   File "main.py", line 245, in on_message
>     f = open("Data\\ChatLog\\Log.txt", "a")

**Comment by NotReeceHarris** [comment]
yh this is completely my fault i forgot to add the log file in the git.

Create a folder called `ChatLog` within the Data folder
Once you have done that Add a file called `Log.txt` within this folder

**Comment by RandomVersion** [comment]
It works now but the commands stats and backpack doesn't seem to work no error too.

**Comment by NotReeceHarris** [comment]
hey give me a msg on discord ill help you out some more, every computer is different it seems :)

**Comment by RandomVersion** [comment]
alr
